name: build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2.6.1
        with:
          distribution: goreleaser
          version: latest
          args: --snapshot --rm-dist
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push latest image
        run: docker push docker.io/odpf/optimus:latest

  documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Installation
        uses: bahmutov/npm-install@v1
        with:
          install-command: yarn
          working-directory: docs
      - name: Build docs
        working-directory: docs
        run: cd docs && yarn build
      - name: Deploy docs
        env:
          GIT_USER: kushsharma
          GIT_PASS: ${{ secrets.GH_PAT }}
          DEPLOYMENT_BRANCH: gh-pages
          CURRENT_BRANCH: main
        working-directory: docs
        run: |
          git config --global user.email "3647166+kushsharma@users.noreply.github.com"
          git config --global user.name "kushsharma"
          yarn deploy
